import os, sys
import buildutils

# region Commandline arguments ================================================================================================

CMD_ARG_RUN_TESTS           = '-tests'              in sys.argv # Run the tests after building
CMD_ARG_REGENERATE_BINDINGS = '-rebind'             in sys.argv # Regenerate the bindings after building
CMD_ARG_MAKE_ANDROID_PROJ   = '-androidproj'        in sys.argv # Create Android project structure for TestRunner
CMD_ARG_MAKE_VS_PROJ        = '-vsproj'             in sys.argv # Create Visual Studio project structure for TestRunner
CMD_ARG_MAKE_XCODE_PROJ     = '-xcodeproj'          in sys.argv # Create XCode project structure for TestRunner

# endregion

# region File paths ===========================================================================================================

FOLDER_STRUCTURE = buildutils.getFolderStructure(os.path.dirname(os.path.abspath(__file__)))

TEST_RUNNER_ROOT_DIR        = FOLDER_STRUCTURE.root   + 'Tools/TestRunner/'
BINDINGS_GENERATOR_ROOT_DIR = FOLDER_STRUCTURE.root   + 'Tools/BindGen/'

MAIN_FILE                    = FOLDER_STRUCTURE.srcDir     + 'zzzz_Unity.c'
TEST_RUNNER_MAIN_FILE        = TEST_RUNNER_ROOT_DIR        + 'zzzz_TestRunner.c'
BINDINGS_GENERATOR_MAIN_FILE = BINDINGS_GENERATOR_ROOT_DIR + 'BindingsGenerator.c'

def getLibraryObjectPath(plt: buildutils.Platform) -> str:
    return FOLDER_STRUCTURE.tmpDir + buildutils.getObjectOutputFileName('unity', plt)

def getLibraryCompileCommand(plt: buildutils.Platform) -> list[str]:
    return buildutils.getCompilationCommand(plt, False, MAIN_FILE, getLibraryObjectPath(plt))

def getLibraryLinkCommand(plt: buildutils.Platform) -> list[str]:
    return buildutils.getStaticLibLinkCommand(
        plt,
        [getLibraryObjectPath(plt)],
        FOLDER_STRUCTURE.libDir + buildutils.getStaticLibOutputFileName('panshilar', plt)
    )

def getTestRunnerBuildCommand(plt: buildutils.Platform) -> list[str]:
    return buildutils.getExecBuildCommand(
        plt,
        True,
        [TEST_RUNNER_MAIN_FILE],
        ['pthread'] if plt.tgt == 'linux' else [],
        FOLDER_STRUCTURE.binDir + buildutils.getExecOutputFileName('TestRunner', plt),
    )

def getBindingsGeneratorBuildCommand(plt: buildutils.Platform) -> list[str]:
    return buildutils.getExecBuildCommand(
        plt,
        True,
        [BINDINGS_GENERATOR_MAIN_FILE],
        ['pthread'] if plt.tgt == 'linux' else [],
        FOLDER_STRUCTURE.binDir + buildutils.getExecOutputFileName('BindingsGenerator', plt),
    )

# endregion

# region Main Logic ===========================================================================================================

def buildLibrary(plt: buildutils.Platform) -> bool:
    return buildutils.runCommand(getLibraryCompileCommand(plt), f'{plt.prettyTgt}-{plt.prettyArch} Library Compile') and \
           buildutils.runCommand(getLibraryLinkCommand(plt),    f'{plt.prettyTgt}-{plt.prettyArch} Library Link')

def buildTestRunner(plt: buildutils.Platform) -> bool:
    return buildutils.runCommand(getTestRunnerBuildCommand(plt), f'{plt.prettyTgt}-{plt.prettyArch} Test Runner Build')

def buildBindingsGenerator(plt: buildutils.Platform) -> bool:
    return buildutils.runCommand(getBindingsGeneratorBuildCommand(plt), f'{plt.prettyTgt}-{plt.prettyArch} Bindings Generator Build')

# endregion

if __name__ == '__main__':
    buildutils.setupVsCodeLspStuff()

    if CMD_ARG_RUN_TESTS:
        tests = [f.rstrip('.c') for f in os.listdir(TEST_RUNNER_ROOT_DIR) if f.endswith('.c') and not f.startswith('zzzz_')]
        tests = sorted(tests)
        outputFilePath = os.path.join(TEST_RUNNER_ROOT_DIR, 'zzzz_GeneratedCombinedTests.c')
        with open(outputFilePath, 'w', encoding='utf-8') as outputFile:
            outputFile.write('// This file is generated by the build script. Do not edit it manually.\n\n')

            for test in tests:
                outputFile.write('#undef MAIN_TEST_FN\n')
                outputFile.write(f'#define MAIN_TEST_FN(ctxArgName) void ZZZZ_Test_{test}(const TestContext* ctxArgName)\n')
                outputFile.write(f'#include "{test}.c"\n')
                outputFile.write('#undef MAIN_TEST_FN\n\n')

            outputFile.write(f'u64 ZZZZ_GetTestsCount(void) {{ return {len(tests)}ULL; }}\n\n')
            outputFile.write('void ZZZZ_GetAllTests(PNSLR_ArraySlice(TestFunctionInfo) fns)\n')
            outputFile.write('{\n')

            i: int = 0
            for test in tests:
                outputFile.write(f'    fns.data[{i}].name = PNSLR_StringLiteral("{test}");\n')
                outputFile.write(f'    fns.data[{i}].fn   = ZZZZ_Test_{test};\n\n')
                i += 1

            outputFile.write('    // done\n')
            outputFile.write('}\n')

    for plt in buildutils.PLATFORMS_TO_BUILD:
        if True and \
            not CMD_ARG_REGENERATE_BINDINGS and \
            not CMD_ARG_RUN_TESTS and \
            not CMD_ARG_MAKE_ANDROID_PROJ and \
            not CMD_ARG_MAKE_VS_PROJ and \
            not CMD_ARG_MAKE_XCODE_PROJ and \
            True: # don't build the library if we are doing something else
            buildLibrary(plt)

        if CMD_ARG_REGENERATE_BINDINGS and (plt.tgt == 'windows' or plt.tgt == 'osx'): # host platforms only
            buildBindingsGenerator(plt)

        if CMD_ARG_RUN_TESTS and (plt.tgt == 'windows' or plt.tgt == 'linux' or plt.tgt == 'osx'): # desktop platforms only
            buildTestRunner(plt)

    if CMD_ARG_MAKE_ANDROID_PROJ:
        buildutils.createAndroidProject(
            appName = 'PanshilarTestRunner',
            pkgName = 'com.panshilar.testrunner',
            projDir = 'Tools/TestRunner/ProjectFiles/TestRunner_Android',
            cxxMain = '',
            cMain   = 'Tools/TestRunner/zzzz_TestRunner.c',
        )

    if CMD_ARG_MAKE_VS_PROJ:
        buildutils.createVisualStudioProject(
            projName = 'PanshilarTestRunner',
            projDir  = 'Tools/TestRunner/ProjectFiles/TestRunner_VisualStudio',
            cxxMain  = '',
            cMain    = 'Tools/TestRunner/zzzz_TestRunner.c',
        )

    if CMD_ARG_MAKE_XCODE_PROJ:
        buildutils.createXCodeProject(
            projName = 'PanshilarTestRunner',
            pkgName  = 'com.panshilar.testrunner',
            projDir  = 'Tools/TestRunner/ProjectFiles/TestRunner_XCode',
            cxxMain  = '',
            cMain    = 'Tools/TestRunner/zzzz_TestRunner.c',
        )

    buildutils.printSummary()

    if len(buildutils.failedProcesses) > 0:
        exit(1)
