// This file is generated by the build script. Do not edit it manually.

#undef MAIN_TEST_FN
#define MAIN_TEST_FN(ctxArgName) void ZZZZ_Test_DefaultHeapTest(const TestContext* ctxArgName)
#include "DefaultHeapTest.c"
#undef MAIN_TEST_FN

u64 ZZZZ_GetTestsCount(void) { return 1; }

void ZZZZ_GetAllTests(ArraySlice(TestFunctionInfo) fns)
{
    fns.data[0].name = PNSLR_STRING_LITERAL("DefaultHeapTest");
    fns.data[0].fn   = ZZZZ_Test_DefaultHeapTest;

    // done
}
